### ISSUE TITLE
Response headers need to be corrected for service on HIVELab servers

### ISSUE THREAD

**Issue by pmcneely** [GW-HIVE/PredictMod#139] opened 2023-09-15 14:31 UTC
The PredictMod app runs correctly in Dockers on a local machine:
![image](https://github.com/GW-HIVE/PredictMod/assets/22220587/b110f8e3-2ede-4aa1-8023-5519a0163ac8)

Running the same Docker containers on the `hivelab.tst.biochemistry.gwu.edu` server results in "disallowed MIME types" (as the headers sent appear to be "text/html" rather than `css` or `js`):
![image](https://github.com/GW-HIVE/PredictMod/assets/22220587/ff426c7e-c1ed-48d5-9a98-0b8a631e878e)

The frontend is served as: Apache reverse proxy (server) -> Gunicorn (docker WSGI service) -> Django (server)

To build & run the system (from this repository root):
`cd vuetify_app`
`npm install`
`cd ../scripts`
`./compile_frontend.sh`   # Transpile/compile JS assets
`./build_frontend.sh`  # Remove previous docker container/image & rebuild
`./build_backend.sh`  # Same, for Flask backend
`./run_frontend.sh`  # <---- Launches GUnicorn/Django. This is where the headers need to be set
`./run_backend.sh`  # To mount the Flask container to internal docker network

Thank you for having a look into this.

**Comment by pmcneely** [comment] 2023-09-15 15:20
@rykahsay Two helpful details I accidentally left out -
- The code is on branch `vue-updates`
- I've configured Apache on the `tst` server to serve the application at the [`predictmod-beta`](https://hivelab.tst.biochemistry.gwu.edu/predictmod-beta) URL

**Comment by rykahsay** [comment] 2023-09-19 02:33
I am not familiar with angular -- but my understanding is that this has to do with the way you are building your application and is better solved at that level. Can you try what they are recommending in this forum?

https://stackoverflow.com/questions/72070748/failed-to-load-module-script-expected-a-javascript-module-script-but-the-server

**Comment by rykahsay** [comment] 2023-09-19 02:34
This error usually happens because you deployment was into a subfolder, so it seems like Angular is fetching you app directly from your base URL, so your html is found when you go to your domain.com/mysubfolder/index.html, but as the Angular fetches your resources from domain.com/index.html instead of domain.com/mysubfolder/index.html; I’m pretty sure this is the cause of your issue. You can resolve it building your app with:

ng build --prod --base-href mysubfolder

**Comment by pmcneely** [comment] 2023-09-19 15:43
Thank you for having a look, @rykahsay. This doesn't look like the solution, but it does mean that I should escalate the issue, so that will be the next step.

**Comment by pmcneely** [comment] 2023-09-21 17:48
Thanks again, Robel. After talking with Dacian I've realized your solution looks correct, just for Angular rather than Vue/Vite so I missed the high level message. Fixing now.

**Comment by lorikrammer** [comment] 2023-09-28 17:47
@pmcneely Closing this ticket as the issue seems to be resolved. If this is incorrect, please reopen. Thanks!

**Closed by lorikrammer** 2023-09-28 17:47 UTC
